import pandas as pd


# 转换关联关系
def convert_relationship(relationship, product_code='08001'):
    if pd.isna(relationship):
        return "关系未知"
    relationship_dict = {
        "U_PERSONAL": "主体",
        "U_PER_LG_COMPANY": "主体作为法人的企业",
        "U_PER_CT_COMPANY": "主体作为企业实际控制人的企业",
        "U_PER_SH_H_COMPANY": "主体作为股东的企业，主体占股>=50%",
        "U_PER_SH_M_COMPANY": "主体作为股东的企业，主体占股>=30%且<50%",
        "U_PER_SH_L_COMPANY": "主体作为股东的企业，主体占股>=20%且<30%",
        "U_PER_SUPERVISOR_COMPANY": "主体担任监事长的企业",
        "U_PER_EXE_DIRECTOR_PERSONAL": "主体担任执行董事的企业",
        "U_PER_GRNERAL_MANAGER_PERSONAL": "主体担任总经理的企业",
        "U_PER_CHAIRMAN_COMPANY": "主体担任董事长的企业",
        "U_PER_SP_PERSONAL": "主体配偶",
        "U_PER_SP_LG_COMPANY": "主体配偶作为企业法人的企业",
        "U_PER_SP_CT_COMPANY": "主体配偶作为企业实际控制人的企业",
        "U_PER_SP_SH_H_COMPANY": "主体配偶作为股东的企业，主体占股>=50%",
        "U_PER_SP_SH_M_COMPANY": "主体配偶作为股东的企业，主体占股>=30%且<50%",
        "U_PER_SP_SH_L_COMPANY": "主体配偶作为股东的企业，主体占股>=20%且<30%",
        "U_PER_PARENTS_PERSONAL": "主体父母",
        "U_PER_CHILDREN_PERSONAL": "主体子女",
        "U_PER_PARTNER_PERSONAL": "主体合伙人",
        "U_PER_REL_PERSONAL": "主体的关联人",
        "U_PER_REL_NA_PERSONAL": "主体的关联人未授权",
        "U_PER_REL_COMPANY": "主体的关联企业",
        "U_PER_GUARANTOR_PERSONAL": "担保人",
        "U_PER_GUARANTOR_COMPANY": "担保企业",
        "U_PER_OTHER": "其它关系",
        "U_COMPANY": "主体企业",
        "U_COMPANY_SH_PERSONAL": "主体企业股东",
        "U_COM_LEGAL_PERSONAL": "主体企业法人",
        "U_COMPANY_SH_COMPANY": "主体企业作为股东的企业，主体占股>=50%",
        "U_COM_CT_PERSONAL": "主体企业实控人",
        "U_COM_CT_NA_PERSONAL": "主体企业实控人未授权",
        "U_COM_CT_SP_PERSONAL": "主体企业实控人配偶",
        "U_COM_CT_SP_NA_PERSONAL": "主体企业实控人配偶未授权",
        "U_COM_CT_CT_COMPANY": "主体企业实际控制人作为企业实际控制人的企业",
        "U_COM_CT_LG_COMPANY": "主体企业实际控制人作为企业法定代表人的企业",
        "U_COM_CT_SH_H_COMPANY": "主体企业实际控制人作为股东的企业，占股>=50%",
        "U_COM_CT_SH_M_COMPANY": "主体企业实际控制人作为股东的企业，30%=<占股<50%",
        "U_COM_CT_SH_L_COMPANY": "主体企业实际控制人作为股东的企业，20%=<占股<30%",
        "U_COM_CT_SP_CT_COMPANY": "主体企业实际控制人配偶作为企业实际控制人的企业",
        "U_COM_CT_SP_LG_COMPANY": "主体企业实际控制人配偶作为企业法定代表人的企业",
        "U_COM_CT_SP_SH_H_COMPANY": "主体企业实际控制人配偶作为股东的企业，占股>=50%",
        "U_COM_CT_SP_SH_M_COMPANY": "主体企业实际控制人配偶作为股东的企业，30%=<占股<50%",
        "U_COM_CT_SP_SH_L_COMPANY": "主体企业实际控制人配偶作为股东的企业，20%=<占股<30%",
        "U_COM_REL_PERSONAL": "主体企业的关联人",
        "U_COM_REL_NA_PERSONAL": "主体企业的关联人未授权",
        "U_COM_REL_COMPANY": "主体企业的关联企业",
        "U_COM_GUARANTOR_PERSONAL": "主体企业担保人",
        "U_COM_GUARANTOR_COMPANY": "主体企业担保企业",
        "U_COM_OTHER": "主体企业的其它关系"
    }
    if product_code == '08003':
        relationship_dict = {
            "U_PERSONAL": "主体",
            "U_PER_LG_COMPANY": "主体作为企业法人的企业",
            # "U_PER_SH_H_COMPANY": "主体在经营信息内所有维护关系为股东的占股>=50%",
            "U_PER_SH_M_COMPANY": "主体在经营信息内所有维护关系为股东的30%=<占股<50%",
            "U_PER_SH_L_COMPANY": "主体在经营信息内所有维护关系为股东的20%=<占股<30%",
            "U_PER_SH_H_COMPANY": "主体在强关联关系里维护的占股>=50%的大股东(股东为企业)",
            "U_PER_SP_PERSONAL": "主体配偶",
            "U_PER_SP_LG_COMPANY": "主体配偶作为企业法人的企业",
            # "U_PER_SP_SH_H_COMPANY": "主体配偶在经营信息内所有维护关系为股东的占股>=50%",
            "U_PER_SP_SH_M_COMPANY": "主体配偶在经营信息内所有维护关系为股东的30%=<占股<50%",
            "U_PER_SP_SH_L_COMPANY": "主体配偶在经营信息内所有维护关系为股东的20%=<占股<30%",
            "U_PER_SP_SH_H_COMPANY": "主体配偶在强关联关系里维护的占股>=50%的大股东(股东为企业)",
            "U_PER_CT_COMPANY": "主体作为企业实际控制人的企业",
            "U_PER_SP_CT_COMPANY": "主体配偶作为企业实际控制人的企业",
            "U_PER_PARENTS_PERSONAL": "主体父母",
            "U_PER_CHILDREN_PERSONAL": "主体子女",
            "U_PER_PARTNER_PERSONAL": "主体合伙人",
            # "U_PER_GUARANTOR_PERSONAL": "个人借款担保人",
            # "U_PER_GUARANTOR_COMPANY": "个人借款担保企业",
            "U_PER_CHAIRMAN_COMPANY": "主体作为董事长的企业",
            "U_PER_SUPERVISOR_COMPANY": "主体作为监事的企业",
            "U_PER_OTHER": "主体其它关系",
            "U_PER_REL_PERSONAL": "主体的关联人",
            "U_PER_REL_NA_PERSONAL": "主体的关联人未授权",
            "U_PER_REL_COMPANY": "主体的关联企业",
            "U_PER_GUARANTOR_PERSONAL": "主体的担保人",
            "U_PER_GUARANTOR_COMPANY": "主体的担保企业",
            "U_COMPANY": "主体企业",
            "U_COMPANY_SH_PERSONAL": "企业股东",
            "U_COM_LEGAL_PERSONAL": "企业法人",
            "U_COMPANY_SH_COMPANY": "主体企业作为股东的关联企业且占股>=50%",
            "U_COM_CT_PERSONAL": "主体企业实际控制人",
            "U_COM_CT_CT_COMPANY": "主体企业实际控制人作为企业实际控制人的企业",
            "U_COM_CT_LG_COMPANY": "主体企业实际控制人作为企业法定代表人的企业",
            "U_COM_CT_SH_H_COMPANY": "主体企业实际控制人作为股东的企业，占股>=50%",
            "U_COM_CT_SH_M_COMPANY": "主体企业实际控制人作为股东的企业，30%=<占股<50%",
            "U_COM_CT_SH_L_COMPANY": "主体企业实际控制人作为股东的企业，20%=<占股<30%",
            "U_COM_CT_SP_PERSONAL": "主体企业实际控制人配偶",
            # "U_COM_GUARANTOR_PERSONAL": "企业借款担保人",
            # "U_COM_GUARANTOR_COMPANY": "企业借款担保企业",
            "U_COM_CT_SP_CT_COMPANY": "主体企业实际控制人配偶作为企业实际控制人的企业",
            "U_COM_CT_SP_LG_COMPANY": "主体企业实际控制人配偶作为企业法定代表人的企业",
            "U_COM_CT_SP_SH_H_COMPANY": "主体企业实际控制人配偶作为股东的企业，占股>=50%",
            "U_COM_CT_SP_SH_M_COMPANY": "主体企业实际控制人配偶作为股东的企业，30%=<占股<50%",
            "U_COM_CT_SP_SH_L_COMPANY": "主体企业实际控制人配偶作为股东的企业，20%=<占股<30%",
            "U_COM_OTHER": "主体企业的其它关系",
            "U_COM_REL_PERSONAL": "主体企业的关联人",
            "U_COM_REL_NA_PERSONAL": "主体企业的关联人未授权",
            "U_COM_REL_COMPANY": "主体企业的关联企业",
            "U_COM_GUARANTOR_PERSONAL": "主体企业的担保人",
            "U_COM_GUARANTOR_COMPANY": "主体企业的担保企业",
        }
    for key in relationship_dict:
        if key == relationship:
            return relationship_dict[key]
    return "关系未知"
